### PR TITLE
Add version 2.0 parsing to fli file

### PR DESCRIPTION
**Pull request by ldssdi**
In the new(1.6) version of Capture there's a new header which needs to be supported to read the fli files. To support reading this new header the _init_.py file had to be changed which is done by distinguishing the old header from the new header to still be able to read the fli files created with older versions of capture. 

In the new version of the header certain parameters are removed such datasize, datatype and hasdarkimage. To accomodate this change there are some new functions added which allows for the old implementation to continue to work but the header file being read differently.

### CODE REVIEW

**Comment by rharkes** [comment]
Thank you for this PR. Will merge it and build a new version.

**Comment by rharkes** [comment]
Would it be possible to get the version and parameters that you require by altering [_get_data_info](https://github.com/rharkes/flifile/blob/master/flifile/__init__.py#L241) instead of storing the entire header in a string?

**Comment by rharkes** [comment]
I've refactored the code. The datatypes are now in a [separate class](https://github.com/rharkes/flifile/blob/master/flifile/datatypes.py), that also has the possibility to store the datatype. I'm not sure how the packing lsb/msb is implemented in the new version. 

For the old version the datatype was set in the header. ``FLIMIMAGE -> LAYOUT -> datatype`
The packing was also in the header, with `lsb` as default. `FLIMIMAGE -> LAYOUT -> packing`

In the new version, if the datatype entry in the header has the bit numbering it in the name, does it overrule an optional packing value  in the header?

**Comment by rharkes** [comment]
Could you try my new [readheader](https://github.com/rharkes/flifile/blob/master/flifile/readheader.py#L14) to see if it parses the header in version 2 well?

**Comment by ldssdi** [comment]
> Thank you for this PR. It looks like you rewrote the reading of the header section, but I don't see why. Reading byte-for-byte and calling `"{END}" not in self.headerString` after each read seems needless when there is already a byte-for-byte reading that triggers on `}` when the chapter name is END. [see line 87-L89](https://github.com/rharkes/flifile/blob/master/flifile/flifile.py#L87-L89)
> 
> Would it be possible to get the version and parameters that you require from `self.header`? You could then write another [_get_data_info](https://github.com/rharkes/flifile/blob/master/flifile/flifile.py#L293) that takes the required information from there.
> 
> Could you maybe share an example file with this new 1.6 version so I can test it?

We looked at the current reading of the header from the `.fli` file and concluded that reading on a byte by byte basis is in fact more efficient. It does however make the code harder to maintain, and more difficult to extend to newer/other version of the `.fli` header, since reading and parsing are intertwined in the current implementation. We prefer maintainability in this particular case, since the reading of the header is extremely fast in either case. We do agree however that we don't need to check the entire string each time, just the last 5 characters should be sufficient. Additionally the old version made a bunch of assumptions on the layout of the `.fli` header that aren't true for header 2.0, and most likely also not for other iterations. Also, splitting the reading and parsing makes it easier to check the version number, as that is already read out when starting the parsing.

**Comment by ldssdi** [comment]
We added test files with different headers

**Comment by ldssdi** [comment]
> Could you try my new [readheader](https://github.com/rharkes/flifile/blob/master/flifile/readheader.py#L14) to see if it parses the header in version 2 well?
> 
> I would also be very glad if we could have a few headers of different versions of the fileformat [here](https://github.com/rharkes/flifile/tree/master/tests/testdata) to run unit tests and verify that they are read well.

I tried using readheader with the filepath to a fli-file as input and unfortunately python gives me an error: "'str' object has no attribute 'open'".  What kind of input is that function expecting?

**Comment by rharkes** [comment]
Readheader expects a Path object.

**Comment by ldssdi** [comment]
> Readheader expects a Path object.
> 
> I'll have a look at the new headers you've uploaded.
> 
> I'd prefer a clear way to import `PixelFormat` so its possible values are in an enumerator. For packing it is easy to add another option like this `GigE` aswell right? Just add it [here](https://github.com/rharkes/flifile/blob/master/flifile/datatypes.py#L9). It seems redundant since the information is in the string that is imported too, but it is a lot cleaner, and easier to expand upon.

In that case I would suggest to handle this as we do internally as well: Make a `PixelFormat` class, that sets the main parameters on construction (bit depth, nr of channels, packing, numpy data type, etc..), which then only need to be set once (when parsing the header).

This class can also define an enum of PixelFormats that can be used to determine which unpacking function needs to be used.
Note that there are many more types of packing (we now also support YUV444. YUV422, YUV411, which packs on a byte level, rather than bit level)

Also note that this can be extended for color formats aswell (like Bayer12p). since currently debayering also isn't supported yet.

**Comment by ldssdi** [comment]
> Readheader expects a Path object.

Using the path object readheader.py parses the 2.0 header correctly.

**Comment by rharkes** [comment]
> > Readheader expects a Path object.
> 
> Using the path object readheader.py parses the 2.0 header correctly.

That's great news. Then lets use that one instead of the one that I wrote 3 years ago. I'd give my past-self some points for speed, but I agree with you on preferring maintainability over speed here. 

I hope the reader is also to your liking? I'd expect the header will sticks with some predictable organization, also in the future, and not just dump key-value-pairs right?

**Comment by rharkes** [comment]
> > Readheader expects a Path object.
> > I'll have a look at the new headers you've uploaded.
> > I'd prefer a clear way to import `PixelFormat` so its possible values are in an enumerator. For packing it is easy to add another option like this `GigE` aswell right? Just add it [here](https://github.com/rharkes/flifile/blob/master/flifile/datatypes.py#L9). It seems redundant since the information is in the string that is imported too, but it is a lot cleaner, and easier to expand upon.
> 
> In that case I would suggest to handle this as we do internally as well: Make a `PixelFormat` class, that sets the main parameters on construction (bit depth, nr of channels, packing, numpy data type, etc..), which then only need to be set once (when parsing the header).
> 
> This class can also define an enum of PixelFormats that can be used to determine which unpacking function needs to be used. Note that there are many more types of packing (we now also support YUV444. YUV422, YUV411, which packs on a byte level, rather than bit level)
> 
> Also note that this can be extended for color formats aswell (like Bayer12p). since currently debayering also isn't supported yet.

I agree. Lets handle it like it is handled internally, that makes it easier for you to maintain as well. So, if I understand correctly. 
`PixelFormat` will be a class that contains the following fields
* `bitdept`  # type: int
* `nr of channels`  # type: int
* `packing`  # type: Packing  (an enumerator)
* `numpy data type`  # type: np.dtype
* `color format`  # type: Colorformat (an enumerator)

Correct?

**Comment by ldssdi** [comment]
> > > Readheader expects a Path object.
> > 
> > 
> > Using the path object readheader.py parses the 2.0 header correctly.
> 
> That's great news. Then lets use that one instead of the one that I wrote 3 years ago. I'd give my past-self some points for speed, but I agree with you on preferring maintainability over speed here.
> 
> I hope the reader is also to your liking? I'd expect the header will sticks with some predictable organization, also in the future, and not just dump key-value-pairs right?

Yes the reader is to our liking, in the near future we most probably won't change the header. We built this with our eyes on the future but never say never. However you want to look at it, at the end of the day it will be a dump of key value pairs.

**Comment by rharkes** [comment]
> > > > Readheader expects a Path object.
> > > 
> > > 
> > > Using the path object readheader.py parses the 2.0 header correctly.
> > 
> > 
> > That's great news. Then lets use that one instead of the one that I wrote 3 years ago. I'd give my past-self some points for speed, but I agree with you on preferring maintainability over speed here.
> > I hope the reader is also to your liking? I'd expect the header will sticks with some predictable organization, also in the future, and not just dump key-value-pairs right?
> 
> Yes the reader is to our liking, in the near future we most probably won't change the header. We built this with our eyes on the future but never say never. However you want to look at it, at the end of the day it will be a dump of key value pairs.

Well, I do like the chapter->section idea for organizing the key value pairs. Especially in microscopy I'm not a fan of writing the whole organization in the key like
`equipment.microscopy.filtercube.emissionfilter.wavelength=[405-500]`.

But the organization the header it is ever abolished, all kvp's will end in up in header['DEFAULT']['DEFAULT'] .

**Comment by ldssdi** [comment]
> > > Readheader expects a Path object.
> > > I'll have a look at the new headers you've uploaded.
> > > I'd prefer a clear way to import `PixelFormat` so its possible values are in an enumerator. For packing it is easy to add another option like this `GigE` aswell right? Just add it [here](https://github.com/rharkes/flifile/blob/master/flifile/datatypes.py#L9). It seems redundant since the information is in the string that is imported too, but it is a lot cleaner, and easier to expand upon.
> > 
> > 
> > In that case I would suggest to handle this as we do internally as well: Make a `PixelFormat` class, that sets the main parameters on construction (bit depth, nr of channels, packing, numpy data type, etc..), which then only need to be set once (when parsing the header).
> > This class can also define an enum of PixelFormats that can be used to determine which unpacking function needs to be used. Note that there are many more types of packing (we now also support YUV444. YUV422, YUV411, which packs on a byte level, rather than bit level)
> > Also note that this can be extended for color formats aswell (like Bayer12p). since currently debayering also isn't supported yet.
> 
> I agree. Lets handle it like it is handled internally, that makes it easier for you to maintain as well. So, if I understand correctly. `PixelFormat` will be a class that contains the following fields
> 
> * `bitdept`  # type: int
> * `nr of channels`  # type: int
> * `packing`  # type: Packing  (an enumerator)
> * `numpy data type`  # type: np.dtype
> * `color format`  # type: Colorformat (an enumerator)
> 
> Correct? It can have loading functions like `loadfromheaderv2` that takes a string. `loadfromheaderv1` that takes a string. `set` / `get` methods for the parameters.

I don't think we need to split bitpacking and bytepacking, we can just use the name of the packing types (as an enum).

Additionally, set methods aren't really needed, since we can just set all fields in the `__init__` functions. In contrast to camera's you cannot change the data type/pixel format in recordings (.fli files), so once it has been set it should remain immutable.

In our C++ code we do have an `operator=()` (assignment) implemented for the pixel format, but that is only used with cameras/live streams. That operator will then set all fields.

Since we already have a pixelformat class in our C++ code we thing it comes in handy that we make a start with the pixelformat class in python.

**Comment by rharkes** [comment]
I just had a closer look at the new files. Seems the organization of de kvp's in chapters and sections is no more and all kvp's are put in `{FLIMIMAGE}`. However, there is also this:
```
{COMMENTS}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
{COMMENTS_END}

{END}
```
at the end of the header, that seams to break with the original convention of chapters, unless `{COMMENTS_END}` is its own chapter. 

Why, if I may ask, wouldn't you make a kvp where the value is in [json](https://www.json.org/json-en.html)? Since it can be on one line it would not bother the original reader. 
```
{FLIMIMAGE}
version = 2.0
jsonheader = '{"FLIMIMAGE": {"INFO": {"version": "1.0", "compression": "0"}, "LAYOUT": {"timeStamp": "2023-02-07 10:21:19", "CaptureVersion": "1.5.8270.17169", "datatype": "UINT12", "channels": "1", "x": "1944", "y": "1472", "z": "1", "phases": "1", "frequencies": "1", "frameRate": "4", "exposureTime": "5007", "filePath": "D:\\\\FliFile1.0(1)_DEV_1AB22C01C4FA_DS_0x0_02HH6.fli", "deviceName": "1800 U-291m", "deviceSerial": "02HH6", "deviceAlias": "DEV_1AB22C01C4FA_DS_0x0", "hasDarkImage": "0", "lutPath": "", "pixelFormat": "Mono12p", "imageSize": "4292352", "timestamps": "2", "triggerOffset": "0"}}, "datastart": 10752}'
```
If a v2 reader encounters version=2.0 it should ignore everything else and continue to read the jsonheader. If you want to make a file that reads in both v1 and v2 readers, you continue with the header in the old style. If it only needs to be readable by v2 you continue with `{END}`. By adhering to standards like json you are making it easier for others to implement, and you can include everything like arrays and numeric values with proper typing.

**Comment by ldssdi** [comment]
> I just had a closer look at the new files. Seems the organization of de kvp's in chapters and sections is no more and all kvp's are put in `{FLIMIMAGE}`. However, there is also this:
> 
> ```
> {COMMENTS}
>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
> {COMMENTS_END}
> 
> {END}
> ```
> 
> at the end of the header, that seams to break with the original convention of chapters, unless `{COMMENTS_END}` is its own chapter.
> 
> Why, if I may ask, wouldn't you make a kvp where the value is in [json](https://www.json.org/json-en.html)? Since it can be on one line it would not bother the original reader.
> 
> ```
> {FLIMIMAGE}
> version = 2.0
> jsonheader = '{"FLIMIMAGE": {"INFO": {"version": "1.0", "compression": "0"}, "LAYOUT": {"timeStamp": "2023-02-07 10:21:19", "CaptureVersion": "1.5.8270.17169", "datatype": "UINT12", "channels": "1", "x": "1944", "y": "1472", "z": "1", "phases": "1", "frequencies": "1", "frameRate": "4", "exposureTime": "5007", "filePath": "D:\\\\FliFile1.0(1)_DEV_1AB22C01C4FA_DS_0x0_02HH6.fli", "deviceName": "1800 U-291m", "deviceSerial": "02HH6", "deviceAlias": "DEV_1AB22C01C4FA_DS_0x0", "hasDarkImage": "0", "lutPath": "", "pixelFormat": "Mono12p", "imageSize": "4292352", "timestamps": "2", "triggerOffset": "0"}}, "datastart": 10752}'
> ```
> 
> If a v2 reader encounters version=2.0 it should ignore everything else and continue to read the jsonheader. If you want to make a file that reads in both v1 and v2 readers, you continue with the header in the old style. If it only needs to be readable by v2 you continue with `{END}`. By adhering to standards like json you are making it easier for others to implement, and you can include everything like arrays and numeric values with proper typing.

We agree that 
 ```
 {COMMENTS}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 {COMMENTS_END}
 
 {END}
 ```
breaks with convention but those were already there in the original header so that wasn't changed in the new header. So it was already there before. 

We agree that changing the header to json would be a good idea, however the header has just changed to version 2.0 and we've just updated the Fiji flim library for this version aswell. We're going to make adding json an internal issue in the software development planning. Note that converting to json does give us some problems, mainly with values that cannot be set before the recording. If a recording is stopped prematurely, the number of frames will be different from the expected value, and changing that can potentially change the size of the header. Currently this is solved by reserving 21 characters for the total number of frames (which can contain a 64 bit number). I suspect that JSON doesn't really care about additional white space around numbers, but it is a consideration we have to have.

**Comment by rharkes** [comment]
Yes, I'd solve that by writing only spaces to the location in the file reserved for the json string. The nr of spaces is based on the current size of your json string with some extra bytes (21 seems fine). Then writing the json string at that location when all parameters are known. Of course checking that it doesn't go over the space. You generally don't want to edit json on a byte level. 

Didn't know there is a Fiji flim library, or are you referring to bioformats?

**Comment by ldssdi** [comment]
> Yes, I'd solve that by writing only spaces to the location in the file reserved for the json string. The nr of spaces is based on the current size of your json string with some extra bytes (21 seems fine). Then writing the json string at that location when all parameters are known. Of course checking that it doesn't go over the space. You generally don't want to edit json on a byte level.
> 
> Didn't know there is a Fiji flim library, or are you referring to bioformats?
> 
> The break with convention isn't really a problem for the header reader anyway, as long as a new chapter (or `{END}`) follows `{COMMENTS_END}`.

About the json, that's what we expected as well. Nice to have it confirmed. 

Yes we're referring to bioformats.

Yes, there's an `{END}` after `{COMMENTS_END}`

**Comment by rharkes** [comment]
Hi @ldssdi ,
I see you added the original .fli files to your repository. I had them truncated to the headersize, because they are used only for automatic testing of the headerfunction. I'd rather not clog up the repository with megabytes of image data. We could make a separate repository somewhere (e.g. zenodo) with example data. 
I also have a lot of .fli files from the past ten years of which a few are probably good to put in a test.

**Comment by ldssdi** [comment]
> Hi @ldssdi , I see you added the original .fli files to your repository. I had them truncated to the headersize, because they are used only for automatic testing of the headerfunction. I'd rather not clog up the repository with megabytes of image data. We could make a separate repository somewhere (e.g. zenodo) with example data. I also have a lot of .fli files from the past ten years of which a few are probably good to put in a test.

That makes sense

We also added a pixelformat class and implemented the new headerreader in flifile.py

**Comment by rharkes** [comment]
Nice, that looks good. [this](https://github.com/ldssdi/flifile/blob/Add-version-2.0-parsing-to-FliFile/flifile/flifile.py#L56-L66) can go I assume. I saw you struggled a bit with the formatting. If you [install black](https://pypi.org/project/black/). You can let it change your formatting for you.

**Comment by rharkes** [comment]
I'd say if the header parsing fails you have bigger problems then not finding the version number.

**Comment by ldssdi** [comment]
> I'd say if the header parsing fails you have bigger problems then not finding the version number.

That is true, and also the reason we made this pull request, because the parsing function failed for the new header.
Additionally you need the version number to properly parse the header, which means it is prudent to obtain the version number first.

**Comment by rharkes** [comment]
No, not really, since readheader.py can read both v1 and v2.

**Comment by ldssdi** [comment]
> No, not really, since readheader.py can read both v1 and v2.

We removed some lines and tried your way to check for the version and it doesn't work for version 2.0 of the header, The way it is right now allows you to open and read files with the 1.0 and 2.0 header and it also is easier to maintain if we decide to change the header in the future.

On top of that the .fli files are deleted from the repo to not clog up the repo.

**Comment by rharkes** [comment]
Just put a slightly changed version of the code I shared in `readheader.py`. 

I understand your method is simpler, but it does restrict the header even further. In your version it must have `version = 2.0` in the first 32 bytes. At the moment this code has no problem with finding the version, even from a completely non standard header:
```
from flifile.readheader import parseheader, tellversion
headerstring = b"# This header has a comment that is not read \n \
my opinion = proprietary file formats take time away\n \
version = 2.0.54.1\n \
{END}"
header = parseheader(headerstring)
> {'DEFAULT': {'DEFAULT': {'my opinion': 'proprietary file formats take time away', 'version': '2.0.54.1'}}}
version = tellversion(header)
> '2.0.54.1'
```
Of course you can make the fileformat any way you want, since there is no public specification anyway and you can define whatever standards for the header. But the more you restrict yourself by saying things like "it must have `version = x.x` in the first 32 bytes." the harder it will be to be backwards compatible and future-proof. For example it will fail if you put `version=2.0` in the first 32 bytes. Or if you decide on a  `version = 10.0`, you'll need to search the first 33 bytes.

However, maybe it is time for a bit of background:
I started with .fli files in 2009 for my master project, because needed a way to read them into Matlab so I could make phasorplots of specific image regions (cellmembranes, I was studying protein-protein interaction at the time). This was not in your software, so I wrote some code for it. In 2016, as post-doc I again encountered .fli files. Still had my old Matlab code, so I adapted it to read de .fli files from the toggel camera.  After that project (2020) everybody moved to python, so I did too and made this package as an exercise in my free time. Also wrote a package for doing some basic frequency domain FLIM. It was fun and I learned something. However, at the moment I work in a microscopy facility and I don't expect I'll ever work with .fli files again. I also don't expect anybody from our institute will ever work with .fli files. Therefore I cannot write this off as work.

So, just let me know when you're happy with your pull request. I will merge it without checking it, and build a new version of the package, and I'll not suggest any more changes.

**Comment by rharkes** [comment]
Hi @ldssdi ,
I have not heard from you since the last post. The current version of the package can read the four files you shared. I find the following means:
```
datameans = {
    "FliFile1.0_DEV_1AB22C01C4FA_DS_0x0_02HH6.fli": 15.753081352601091,
    "FliFile2.0_DEV_1AB22C01C4FA_DS_0x0_02HH6.fli": 45.16429558899177,
    "FliFile1.0(1)_DEV_1AB22C01C4FA_DS_0x0_02HH6.fli": 260.88322276458223,
    "FliFile2.0(1)_DEV_1AB22C01C4FA_DS_0x0_02HH6.fli": 712.4043131248322,
}
```
Is this the same as what you would expect to find?

I'm closing this pull request, but feel free to make a new one if there are newer versions of the file format.

**Pull request closed without merging**
